### ISSUE TITLE
setSocket(Socket socket) method missing in WebSocket.java

### ISSUE THREAD

**Issue by kimalser** [elirex/android-faye-client#2]
The method setSocket() is used in FayeClient.java, specifically in openWebSocketConnection() method, however there is no such method in neither WebSocket class, nor its parent - WebSocketClient class.

**Comment by elirex** [comment]
You can try to replace compile files('libs/Java-WebSocket-1.2.1.jar') to  compile 'org.java-websocket:Java-WebSocket:1.3.0' at build.gradle

**Comment by elirex** [comment]
No feedback => closing.
